const KEY="niveshnyay_cases_v1", $=id=>document.getElementById(id);let cases=JSON.parse(localStorage.getItem(KEY)||"[]"),current=[];
const evidence=["Account / transaction record","Written complaint and response","Relevant correspondence","Supporting screenshots"];
function classify(s){s=s.toLowerCase();if(/otp|fraud|scam|cyber|phishing/.test(s))return"Fraud / cybercrime";if(/bank|upi|payment|utr/.test(s))return"Bank / payment issue";if(/insurance|policy|premium/.test(s))return"Insurance / intermediary issue";if(/mutual fund|amc|sip/.test(s))return"Mutual fund / AMC issue";if(/demat|registrar|corporate action/.test(s))return"Demat / registrar issue";if(/broker|trading|trade|charge|contract note|ledger/.test(s))return"Broker / trading issue";return"Other investor grievance"}
function draft(c,s){return"Subject: Grievance regarding "+(c||"[category]")+"\n\nDear Sir/Madam,\n\nI am writing to raise a grievance regarding:\n\n"+(s||"[BRIEFLY DESCRIBE THE EVENTS]")+"\n\nI request that you review the matter, explain the basis for the action or charge, correct the issue where applicable, and provide a written response with a clear reference number.\n\nEvidence available:\n[LIST YOUR ATTACHMENTS]\n\nPlease acknowledge receipt of this complaint.\n\nRegards,\n[NAME]"}
function renderEvidence(){current=evidence;$("evidenceList").innerHTML=current.map((x,i)=>'<label class="check-item"><input type="checkbox" data-evidence="'+i+'"><span>'+x+"</span></label>").join("")}
function analyze(){const s=$("concern").value.trim();if(!s){$("concern").focus();return}const c=classify(s);$("category").value=c;renderEvidence();$("draft").value=draft(c,s);$("draftStatus").textContent="Draft ready";document.querySelector(".plan").scrollIntoView({behavior:"smooth"})}
$("concern").oninput=e=>$("charCount").textContent=e.target.value.length.toLocaleString()+" / 5,000";$("storyForm").onsubmit=e=>{e.preventDefault();analyze()};
$("sampleBtn").onclick=()=>{$("concern").value="I invested through a broker and noticed a charge on my account that I did not understand. I contacted support, but the explanation did not match the statement.";analyze()};
$("category").onchange=()=>{renderEvidence();if($("concern").value)$("draft").value=draft($("category").value,$("concern").value)};
$("resetDraft").onclick=()=>{$("draft").value="";$("category").value="";$("evidenceList").innerHTML="";$("draftStatus").textContent="Unsaved"};
$("copyDraft").onclick=async()=>{try{await navigator.clipboard.writeText($("draft").value);$("copyDraft").textContent="Copied ✓";setTimeout(()=>$("copyDraft").textContent="Copy draft",1200)}catch{}};
function state(){return{concern:$("concern").value,category:$("category").value,evidence:[...document.querySelectorAll("[data-evidence]:checked")].map(x=>current[+x.dataset.evidence]),draft:$("draft").value,stage:$("stage").value,reference:$("reference").value,receiptDate:$("receiptDate").value,notes:$("notes").value,updatedAt:new Date().toISOString()}}
$("saveCase").onclick=()=>{const c=state();if(!c.concern&&!c.draft)return;cases.unshift({...c,id:Date.now(),title:c.category||"Investor grievance"});localStorage.setItem(KEY,JSON.stringify(cases));renderCases();$("draftStatus").textContent="Saved";document.querySelector("#cases").scrollIntoView({behavior:"smooth"})};
$("exportCase").onclick=()=>{const b=new Blob([JSON.stringify(state(),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="niveshnyay-case-pack.json";a.click();URL.revokeObjectURL(a.href)};
function renderCases(){const q=$("caseSearch").value.toLowerCase(),f=$("caseFilter").value,v=cases.filter(c=>(!q||JSON.stringify(c).toLowerCase().includes(q))&&(f==="all"||c.stage===f));$("caseList").innerHTML=v.length?v.map(c=>'<article class="case-item"><div><div class="case-meta"><span class="tag">'+c.category+'</span><span class="tag">'+c.stage+'</span></div><h4>'+safe(c.title)+'</h4><p>'+safe((c.concern||"No summary").slice(0,180))+'</p></div><div class="case-actions"><button class="btn outline" onclick="loadCase('+c.id+')">Open</button><button class="text-link" onclick="deleteCase('+c.id+')">Delete</button></div></article>').join(""):'<div class="empty">No saved cases yet. Start with your story above.</div>'}
function safe(s){return String(s).replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[x]))}
window.loadCase=id=>{const c=cases.find(x=>x.id===id);if(!c)return;$("concern").value=c.concern||"";$("concern").dispatchEvent(new Event("input"));$("category").value=c.category||"";renderEvidence();$("draft").value=c.draft||"";$("stage").value=c.stage||"Drafting";$("reference").value=c.reference||"";$("receiptDate").value=c.receiptDate||"";$("notes").value=c.notes||"";location.hash="workspace"};window.deleteCase=id=>{cases=cases.filter(x=>x.id!==id);localStorage.setItem(KEY,JSON.stringify(cases));renderCases()};
$("caseSearch").oninput=renderCases;$("caseFilter").onchange=renderCases;$("refreshCases").onclick=renderCases;$("newCase").onclick=()=>location.hash="workspace";
document.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>{$("quizResult").textContent=b.dataset.answer==="good"?"Correct. Never share OTPs; verify through an official channel.":"Red flag. Never share an OTP with a caller.";});
$("signInBtn").onclick=()=>$("signInModal").showModal();renderCases();